const M = {
  created_at: "2026-06-14T00:00:00Z",
  updated_at: "2026-06-14T00:00:00Z",
  created_by: "socrates_admin",
  last_updated_by: "socrates_admin",
  version: "1.0",
  status: "published" as const,
};

export const questions = [
  {
    id: "q_active_recall_generic_01",
    type: "question" as const,
    relations: {
      concept_ids: ["concept_active_recall"],
      related_card_ids: ["card_active_recall_def"],
    },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "generic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "Which study activity best exemplifies active recall?",
      options: [
        { id: "opt_A", text: "Re-reading highlighted notes" },
        { id: "opt_B", text: "Closing the book and writing everything you remember" },
        { id: "opt_C", text: "Watching a lecture video again" },
        { id: "opt_D", text: "Copying definitions verbatim" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Active recall requires retrieval from memory without cues.",
      distractors: {
        opt_A: "Highlighting is passive review.",
        opt_C: "Re-watching is recognition, not recall.",
        opt_D: "Copying does not test memory.",
      },
    },
    editorial: { difficulty: "easy" as const, tags: ["core"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_active_recall_establish_01",
    type: "question" as const,
    relations: { concept_ids: ["concept_active_recall"], related_card_ids: [] },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "establishment" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "The testing effect shows that:",
      options: [
        { id: "opt_A", text: "More study time always equals better retention" },
        { id: "opt_B", text: "Retrieval practice improves long-term retention vs. restudy" },
        { id: "opt_C", text: "Cramming is optimal for durable memory" },
        { id: "opt_D", text: "Passive review outperforms quizzing" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Retrieval strengthens memory more than passive restudy of the same material.",
      distractors: {},
    },
    editorial: { difficulty: "easy" as const, tags: ["establishment"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_forgetting_curve_generic_01",
    type: "question" as const,
    relations: { concept_ids: ["concept_forgetting_curve"], related_card_ids: ["card_forgetting_curve_def"] },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "generic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "According to the forgetting curve, memory retention without review:",
      options: [
        { id: "opt_A", text: "Stays flat indefinitely" },
        { id: "opt_B", text: "Decays exponentially over time" },
        { id: "opt_C", text: "Improves with time" },
        { id: "opt_D", text: "Depends only on initial study duration" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: { general: "Ebbinghaus showed rapid initial decay, then slower decline.", distractors: {} },
    editorial: { difficulty: "easy" as const, tags: ["core"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_spaced_rep_diagnostic_01",
    type: "question" as const,
    relations: {
      concept_ids: ["concept_spaced_repetition"],
      related_card_ids: ["card_spaced_rep_def"],
    },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "diagnostic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "A student reviews all cards every day regardless of performance. What misconception does this reflect?",
      options: [
        { id: "opt_A", text: "Spacing intervals should adapt as material is learned" },
        { id: "opt_B", text: "Fixed daily review is always optimal" },
        { id: "opt_C", text: "Active recall is unnecessary with enough repetition" },
        { id: "opt_D", text: "The forgetting curve does not apply to flashcards" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Spaced repetition increases intervals — fixed daily review ignores learned stability.",
      distractors: { opt_A: "This is the correct principle, not a misconception." },
    },
    editorial: { difficulty: "medium" as const, tags: ["diagnostic"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_fsrs_diagnostic_01",
    type: "question" as const,
    relations: { concept_ids: ["concept_fsrs"], related_card_ids: ["card_fsrs_stability_def"] },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "diagnostic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "In FSRS, a learner marks every card 'Again' even when they knew the answer. What is the likely scheduling impact?",
      options: [
        { id: "opt_A", text: "Stability increases rapidly" },
        { id: "opt_B", text: "Intervals stay short; stability does not grow" },
        { id: "opt_C", text: "Difficulty drops to minimum" },
        { id: "opt_D", text: "Cards are permanently suppressed" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "'Again' signals failed recall — FSRS will not extend intervals.",
      distractors: {},
    },
    editorial: { difficulty: "medium" as const, tags: ["diagnostic", "fsrs"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_fsrs_targeted_01",
    type: "question" as const,
    relations: { concept_ids: ["concept_fsrs"], related_card_ids: ["card_fsrs_difficulty_def"] },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "targeted" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "A card with high FSRS difficulty will tend to have:",
      options: [
        { id: "opt_A", text: "Longer intervals than an easy card" },
        { id: "opt_B", text: "Shorter intervals than an easy card" },
        { id: "opt_C", text: "No scheduled reviews" },
        { id: "opt_D", text: "Identical intervals regardless of grade" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Higher difficulty means the item is harder to retain — FSRS schedules more frequent reviews.",
      distractors: {},
    },
    editorial: { difficulty: "medium" as const, tags: ["targeted"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_concept_map_generic_01",
    type: "question" as const,
    relations: { concept_ids: ["concept_concept_maps"], related_card_ids: ["card_concept_map_def"] },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "generic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "In a Socrates concept map, a 'prerequisite' relationship means:",
      options: [
        { id: "opt_A", text: "Both concepts must be studied simultaneously" },
        { id: "opt_B", text: "The from-concept should be learned before the to-concept" },
        { id: "opt_C", text: "The concepts are unrelated" },
        { id: "opt_D", text: "Only certification questions link the concepts" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: { general: "Prerequisites enforce learning order in the knowledge graph.", distractors: {} },
    editorial: { difficulty: "easy" as const, tags: ["core"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_event_sourcing_diagnostic_01",
    type: "question" as const,
    relations: { concept_ids: ["concept_event_sourcing"], related_card_ids: ["card_event_sourcing_def"] },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "diagnostic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "A developer updates the card schedule document directly in Firestore instead of appending events. What breaks?",
      options: [
        { id: "opt_A", text: "Nothing — views are the source of truth" },
        { id: "opt_B", text: "Audit trail and idempotent replay from the event log" },
        { id: "opt_C", text: "Only the UI theme" },
        { id: "opt_D", text: "Concept map layout" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Event sourcing derives state from events — direct view edits bypass the log.",
      distractors: {},
    },
    editorial: { difficulty: "hard" as const, tags: ["diagnostic"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_certification_misconception_01",
    type: "question" as const,
    relations: {
      concept_ids: ["concept_mastery_certification"],
      related_card_ids: ["card_certification_def"],
    },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "misconception_directed" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "After partial certification, Socrates will:",
      options: [
        { id: "opt_A", text: "Suppress all cards in the library permanently" },
        { id: "opt_B", text: "Apply policy based on outcome — may adjust scheduling for related cards" },
        { id: "opt_C", text: "Delete the concept from the map" },
        { id: "opt_D", text: "Skip FSRS entirely" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Certification outcomes (full/partial/none) drive scheduling policy, not blanket suppression.",
      distractors: { opt_A: "Partial mastery does not mean permanent suppression of everything." },
    },
    editorial: { difficulty: "hard" as const, tags: ["certification"] },
    media: [],
    references: [],
    metadata: M,
  },
  {
    id: "q_rel_active_spaced_01",
    type: "question" as const,
    relations: {
      concept_ids: ["concept_active_recall", "concept_spaced_repetition"],
      related_card_ids: ["card_rel_active_to_spaced"],
    },
    source: { origin: "validated" as const, provider: "Socrates_Internal", subscription_required: false },
    classification: {
      question_type: "mcq" as const,
      usage_role: "generic" as const,
      cognitive_level: "mechanism" as const,
    },
    content: {
      stem: "Why is active recall a prerequisite for understanding spaced repetition?",
      options: [
        { id: "opt_A", text: "Spacing only works for visual learners" },
        { id: "opt_B", text: "Spaced reviews are retrieval events — recall is what you do at each review" },
        { id: "opt_C", text: "FSRS requires multiple-choice questions only" },
        { id: "opt_D", text: "Active recall replaces the need for spacing" },
      ],
      correct_option_id: "opt_B",
    },
    explanations: {
      general: "Spacing schedules when; active recall is the practice performed at each interval.",
      distractors: {},
    },
    editorial: { difficulty: "medium" as const, tags: ["relationship"] },
    media: [],
    references: [],
    metadata: M,
  },
];
