import type { MedL3Spec } from "./_medicineL3Generator.js";

const CARD = "Cardiology";
const PULM = "Pulmonology";
const NEPH = "Nephrology & Fluid Balance";
const GI = "Gastroenterology & Hepatology";
const ENDO = "Endocrinology & Metabolism";
const HEME = "Hematology & Oncology";
const NEURO = "Neurology";
const PSYCH = "Psychiatry & Behavioral Health";
const ID = "Infectious Disease";
const MSK = "Musculoskeletal & Rheumatology";
const DERM = "Dermatology";
const OBGYN = "Obstetrics & Gynecology";
const SURG = "Surgery & Perioperative Care";

const O = { source: "OpenStax Anatomy and Physiology 2e" };
const S = { source: "NCBI StatPearls" };

function c(
  shortName: string,
  l2: string,
  cluster: string,
  title: string,
  definition: string,
  summary: string,
  source: { source: string; chapter?: string; section?: string },
  prerequisites?: string[],
  unlocks?: string[],
): MedL3Spec {
  return {
    shortName,
    l2,
    cluster,
    title,
    definition,
    summary,
    prerequisites,
    unlocks,
    source: {
      source: source.source,
      chapter: source.chapter ?? "TBD",
      section: source.section ?? "TBD",
    },
  };
}

export const CLINICAL_SPECS: MedL3Spec[] = [
  // Cardiology (12)
  c("arrhythmia_mechanisms", CARD, "Electrophysiology", "Arrhythmia Mechanisms", "Reentry, enhanced automaticity, and triggered activity disrupting normal cardiac rhythm.", "Reentry requires unidirectional block and slow conduction. Long QT predisposes to torsades de pointes.", { ...S, chapter: "Arrhythmias", section: "Mechanisms" }, ["spine_biology_l3_action_potential"]),
  c("atrial_fibrillation_management", CARD, "Arrhythmias", "Atrial Fibrillation Management", "Rate versus rhythm control, anticoagulation by stroke risk, and cardioversion considerations.", "CHA2DS2-VASc guides anticoagulation. Rate control often uses beta-blockers or calcium channel blockers.", { ...S, chapter: "Atrial Fibrillation", section: "Management" }),
  c("acute_coronary_syndrome", CARD, "Ischemic Heart Disease", "Acute Coronary Syndrome", "Unstable angina, NSTEMI, and STEMI spectrum with plaque rupture and myocardial ischemia.", "STEMI requires reperfusion therapy. Troponin elevation distinguishes MI from unstable angina.", { ...S, chapter: "ACS", section: "Overview" }),
  c("heart_failure_diagnosis_management", CARD, "Heart Failure", "Heart Failure Diagnosis and Management", "Reduced versus preserved ejection fraction with neurohormonal blockade and diuretic therapy.", "HFrEF benefits from ACE inhibitors, beta-blockers, and MRAs. Volume overload warrants loop diuretics.", { ...S, chapter: "Heart Failure", section: "Management" }),
  c("valvular_heart_disease", CARD, "Valvular Disease", "Valvular Heart Disease", "Stenosis and regurgitation of aortic and mitral valves with hemodynamic consequences.", "Aortic stenosis causes syncope, angina, and heart failure. Mitral regurgitation volume overloads left ventricle.", { ...S, chapter: "Valvular Disease", section: "Overview" }),
  c("hypertension_clinical_management", CARD, "Hypertension", "Hypertension Clinical Management", "Diagnosis, secondary causes, target organ damage, and stepwise pharmacotherapy.", "Resistant hypertension warrants secondary cause workup. Hypertensive emergency requires IV agents.", { ...S, chapter: "Hypertension", section: "Management" }),
  c("pericardial_disease", CARD, "Pericardial Disease", "Pericardial Disease", "Acute pericarditis, effusion, tamponade, and constrictive physiology affecting diastolic filling.", "Beck triad suggests tamponade. Constriction shows pericardial knock and Kussmaul sign.", { ...S, chapter: "Pericardial Disease", section: "Overview" }),
  c("syncope_evaluation", CARD, "Clinical Cardiology", "Syncope Evaluation", "Reflex, cardiac, orthostatic, and neurologic causes distinguished by history and provocative testing.", "Cardiac syncope carries highest mortality risk. Carotid sinus massage assesses reflex syncope.", { ...S, chapter: "Syncope", section: "Evaluation" }),
  c("ecg_interpretation_basics", CARD, "Diagnostics", "ECG Interpretation Basics", "Rate, rhythm, axis, intervals, and ischemic ST-T wave pattern recognition.", "ST elevation localizes infarct territory. Wide QRS suggests ventricular origin or bundle branch block.", { ...O, chapter: "19", section: "19.5" }),
  c("cardiomyopathies", CARD, "Myocardial Disease", "Cardiomyopathies", "Dilated, hypertrophic, and restrictive patterns with genetic and acquired etiologies.", "HCM risks sudden death in young athletes. Restrictive disease stiffens ventricles impairing filling.", { ...S, chapter: "Cardiomyopathy", section: "Types" }),
  c("infective_endocarditis", CARD, "Infectious Cardiology", "Infective Endocarditis", "Valve infection with vegetations, embolic phenomena, and blood culture-directed therapy.", "IV drug use predisposes to tricuspid involvement. Duke criteria integrate clinical and echo findings.", { ...S, chapter: "Endocarditis", section: "Diagnosis" }),
  c("lipid_management_ascvd", CARD, "Preventive Cardiology", "Lipid Management and ASCVD Risk", "Statin therapy, risk calculators, and LDL targets for atherosclerotic cardiovascular disease prevention.", "High-intensity statins lower LDL and event rates. Familial hypercholesterolemia warrants early treatment.", { ...S, chapter: "Lipids", section: "Management" }),

  // Pulmonology (9)
  c("asthma_diagnosis_management", PULM, "Obstructive Lung Disease", "Asthma Diagnosis and Management", "Reversible bronchospasm with stepwise controller and reliever therapy including inhaled corticosteroids.", "Spirometry shows obstructive pattern with bronchodilator response. SABA relieves acute symptoms.", { ...S, chapter: "Asthma", section: "Management" }),
  c("copd_clinical_management", PULM, "Obstructive Lung Disease", "COPD Clinical Management", "Progressive airflow limitation managed with bronchodilators, pulmonary rehab, and oxygen when indicated.", "GOLD staging guides therapy. Acute exacerbations often triggered by infection.", { ...S, chapter: "COPD", section: "Management" }),
  c("pulmonary_embolism", PULM, "Vascular Lung Disease", "Pulmonary Embolism", "Thromboembolic occlusion of pulmonary arteries causing hypoxemia and right heart strain.", "Wells score and D-dimer guide workup. Anticoagulation is cornerstone of treatment.", { ...S, chapter: "Pulmonary Embolism", section: "Management" }),
  c("pneumonia_clinical_approach", PULM, "Infectious Pulmonology", "Pneumonia Clinical Approach", "Community and hospital-acquired pneumonia with severity scoring and empiric antibiotics.", "CURB-65 estimates mortality risk. Atypical coverage considered in outpatient regimens.", { ...S, chapter: "Pneumonia", section: "Management" }),
  c("interstitial_lung_disease", PULM, "Restrictive Lung Disease", "Interstitial Lung Disease", "Fibrotic and inflammatory parenchymal disorders reducing compliance and diffusing capacity.", "Idiopathic pulmonary fibrosis shows honeycombing on CT. Connective tissue disease may cause ILD.", { ...S, chapter: "ILD", section: "Overview" }),
  c("pleural_effusion_evaluation", PULM, "Pleural Disease", "Pleural Effusion Evaluation", "Transudative versus exudative effusions by Light criteria with diagnostic thoracentesis.", "Exudates suggest inflammation or malignancy. Large effusions cause dyspnea requiring drainage.", { ...S, chapter: "Pleural Effusion", section: "Evaluation" }),
  c("acute_respiratory_distress_syndrome", PULM, "Critical Care Pulmonology", "Acute Respiratory Distress Syndrome", "Noncardiogenic pulmonary edema with severe hypoxemia requiring lung-protective ventilation.", "Berlin criteria define ARDS by timing, imaging, and oxygenation. Low tidal volume ventilation improves outcomes.", { ...S, chapter: "ARDS", section: "Management" }),
  c("sleep_apnea", PULM, "Sleep Medicine", "Obstructive Sleep Apnea", "Recurrent upper airway collapse during sleep causing hypoxemia, fragmentation, and daytime somnolence.", "CPAP is first-line therapy. OSA associates with hypertension and cardiovascular disease.", { ...S, chapter: "Sleep Apnea", section: "Management" }),
  c("lung_cancer_evaluation", PULM, "Oncologic Pulmonology", "Lung Cancer Evaluation", "Solitary nodule assessment, staging, and histologic subtypes guiding treatment.", "Smoking is major risk factor. Small cell versus non-small cell determines therapy approach.", { ...S, chapter: "Lung Cancer", section: "Evaluation" }),

  // Nephrology & Fluid Balance (9)
  c("chronic_kidney_disease_staging", NEPH, "Chronic Kidney Disease", "Chronic Kidney Disease Staging", "GFR and albuminuria categories guiding monitoring, complication prevention, and referral.", "CKD complications include anemia, bone disease, and cardiovascular risk. Dialysis considered at end stage.", { ...S, chapter: "CKD", section: "Staging" }),
  c("acute_kidney_injury_management", NEPH, "Acute Kidney Injury", "Acute Kidney Injury Management", "Prerenal, intrinsic, and postrenal AKI with fluid resuscitation, nephrotoxin avoidance, and renal replacement.", "FeNa helps distinguish prerenal from ATN. Indications for dialysis include refractory hyperkalemia.", { ...S, chapter: "AKI", section: "Management" }),
  c("electrolyte_disorders_sodium", NEPH, "Electrolytes", "Sodium Disorders", "Hyponatremia and hypernatremia reflecting water balance disturbances with osmotic correction principles.", "Acute hyponatremia corrected slowly to avoid osmotic demyelination. Hypernatremia implies water deficit.", { ...S, chapter: "Hyponatremia", section: "Management" }),
  c("electrolyte_disorders_potassium", NEPH, "Electrolytes", "Potassium Disorders", "Hypokalemia and hyperkalemia with ECG changes and emergent membrane stabilization for severe hyperkalemia.", "Peaked T waves suggest hyperkalemia. Insulin and glucose shift potassium intracellularly temporizing.", { ...S, chapter: "Hyperkalemia", section: "Management" }),
  c("acid_base_disorders_clinical", NEPH, "Acid-Base", "Clinical Acid-Base Disorders", "Metabolic and respiratory acidosis-alkalosis diagnosed by pH, PaCO2, and bicarbonate with compensation.", "Anion gap metabolic acidosis includes MUDPILES causes. Winter formula estimates respiratory compensation.", { ...S, chapter: "Acid-Base", section: "Diagnosis" }),
  c("nephrotic_syndrome", NEPH, "Glomerular Disease", "Nephrotic Syndrome", "Heavy proteinuria, hypoalbuminemia, edema, and hyperlipidemia from glomerular permeability defects.", "Minimal change disease common in children. Membranous nephropathy associates with PLA2R antibodies.", { ...S, chapter: "Nephrotic Syndrome", section: "Overview" }),
  c("nephritic_syndrome", NEPH, "Glomerular Disease", "Nephritic Syndrome", "Hematuria, RBC casts, hypertension, and reduced GFR from glomerular inflammation.", "Poststreptococcal GN follows infection. RPGN requires urgent immunosuppression or plasmapheresis.", { ...S, chapter: "Nephritic Syndrome", section: "Overview" }),
  c("urinary_tract_infection", NEPH, "Genitourinary Infections", "Urinary Tract Infection", "Cystitis versus pyelonephritis with empiric antibiotics guided by resistance patterns.", "Uncomplicated cystitis treated short course in women. Fever and flank pain suggest pyelonephritis.", { ...S, chapter: "UTI", section: "Management" }),
  c("kidney_stones", NEPH, "Urolithiasis", "Kidney Stones", "Calcium, uric acid, struvite, and cystine stones with imaging, analgesia, and prevention strategies.", "Calcium oxalate stones are most common. Thiazides reduce calcium stone recurrence.", { ...S, chapter: "Nephrolithiasis", section: "Management" }),

  // Gastroenterology & Hepatology (8)
  c("gerd_and_peptic_ulcer_disease", GI, "Upper GI", "GERD and Peptic Ulcer Disease", "Acid reflux and mucosal ulceration managed with PPIs and H. pylori eradication when indicated.", "Alarm features warrant endoscopy. H. pylori quadruple therapy clears infection.", { ...S, chapter: "GERD", section: "Management" }),
  c("inflammatory_bowel_disease", GI, "Inflammatory Bowel Disease", "Inflammatory Bowel Disease", "Crohn disease and ulcerative colitis with immunomodulator and biologic therapy.", "UC is continuous colonic disease; Crohn is transmural with skip lesions. Biologics target TNF and integrins.", { ...S, chapter: "IBD", section: "Management" }),
  c("cirrhosis_and_portal_hypertension", GI, "Hepatology", "Cirrhosis and Portal Hypertension", "Chronic liver injury causing ascites, varices, encephalopathy, and hepatorenal syndrome.", "Nonselective beta-blockers reduce variceal bleed risk. Lactulose treats hepatic encephalopathy.", { ...S, chapter: "Cirrhosis", section: "Complications" }),
  c("viral_hepatitis", GI, "Hepatology", "Viral Hepatitis", "Hepatitis A, B, C, D, and E with serologic patterns and antiviral or supportive therapy.", "HBsAg indicates active B infection. Direct-acting antivirals cure most hepatitis C.", { ...S, chapter: "Hepatitis", section: "Overview" }),
  c("acute_pancreatitis", GI, "Pancreatic Disease", "Acute Pancreatitis", "Gallstone and alcohol etiologies with inflammatory cascade, pain control, and fluid resuscitation.", "Lipase elevation supports diagnosis. Severe pancreatitis risks necrosis and organ failure.", { ...S, chapter: "Pancreatitis", section: "Acute" }),
  c("gi_bleeding_evaluation", GI, "GI Emergencies", "GI Bleeding Evaluation", "Upper versus lower sources, hemodynamic resuscitation, and endoscopic or angiographic hemostasis.", "Melena suggests upper GI source. Rockall and Blatchford scores risk-stratify.", { ...S, chapter: "GI Bleeding", section: "Evaluation" }),
  c("irritable_bowel_syndrome", GI, "Functional GI", "Irritable Bowel Syndrome", "Chronic abdominal pain with altered bowel habits diagnosed by criteria after excluding organic disease.", "Subtypes include IBS-C, IBS-D, and mixed. Dietary and neuromodulator therapies help symptoms.", { ...S, chapter: "IBS", section: "Management" }),
  c("colorectal_cancer_screening", GI, "GI Oncology", "Colorectal Cancer Screening", "Colonoscopy and stool-based tests detecting adenomas and cancer in average-risk populations.", "Adenomatous polyps are premalignant. Screening begins age 45 in many guidelines.", { ...S, chapter: "Colorectal Cancer", section: "Screening" }),

  // Endocrinology & Metabolism (8)
  c("diabetes_mellitus_type1_type2", ENDO, "Diabetes", "Diabetes Mellitus Type 1 and Type 2", "Autoimmune insulin deficiency versus insulin resistance with distinct management and complication screening.", "DKA is type 1 emergency. Metformin is first-line in type 2 without contraindications.", { ...S, chapter: "Diabetes", section: "Types" }),
  c("diabetic_ketoacidosis", ENDO, "Diabetes Emergencies", "Diabetic Ketoacidosis", "Insulin deficiency with hyperglycemia, ketosis, and anion gap acidosis requiring fluid and insulin therapy.", "Serum beta-hydroxybutyrate confirms ketosis. Potassium repletion critical during insulin treatment.", { ...S, chapter: "DKA", section: "Management" }),
  c("thyroid_disorders_hypo_hyper", ENDO, "Thyroid Disease", "Hypothyroidism and Hyperthyroidism", "TSH-centered diagnosis with levothyroxine replacement or antithyroid drugs, radioiodine, or surgery.", "Primary hypothyroidism shows high TSH and low free T4. Graves disease causes hyperthyroidism with autoantibodies.", { ...S, chapter: "Thyroid", section: "Disorders" }),
  c("adrenal_insufficiency", ENDO, "Adrenal Disorders", "Adrenal Insufficiency", "Primary Addison versus secondary cortisol deficiency with mineralocorticoid loss in primary disease.", "Hyperpigmentation suggests primary insufficiency. Stress steroid dosing prevents adrenal crisis.", { ...S, chapter: "Adrenal Insufficiency", section: "Management" }),
  c("cushing_syndrome", ENDO, "Adrenal Disorders", "Cushing Syndrome", "Excess cortisol from exogenous steroids, adrenal adenoma, or ACTH-dependent pituitary or ectopic sources.", "Dexamethasone suppression and ACTH level differentiate etiologies. Moon facies and striae are clinical clues.", { ...S, chapter: "Cushing", section: "Diagnosis" }),
  c("pituitary_disorders", ENDO, "Pituitary Disease", "Pituitary Disorders", "Adenomas causing hormone hypersecretion or hypopituitarism with visual field defects when suprasellar.", "Prolactinoma treated with dopamine agonists. Acromegaly from GH excess causes enlargement features.", { ...S, chapter: "Pituitary", section: "Adenomas" }),
  c("calcium_parathyroid_disorders", ENDO, "Calcium Metabolism", "Calcium and Parathyroid Disorders", "Hyperparathyroidism and hypoparathyroidism altering serum calcium, phosphate, and bone turnover.", "Primary hyperparathyroidism causes stones, bones, groans, and moans. Hypocalcemia prolongs QT interval.", { ...S, chapter: "Hyperparathyroidism", section: "Overview" }),
  c("obesity_and_metabolic_syndrome", ENDO, "Metabolic Disease", "Obesity and Metabolic Syndrome", "Central adiposity with insulin resistance, dyslipidemia, and hypertension increasing cardiometabolic risk.", "Lifestyle intervention is foundation. GLP-1 agonists aid weight loss and glycemic control.", { ...S, chapter: "Obesity", section: "Management" }),

  // Hematology & Oncology (8)
  c("anemia_diagnostic_approach", HEME, "Anemia", "Anemia Diagnostic Approach", "Reticulocyte count, MCV, and peripheral smear guiding mechanistic workup of anemia.", "High reticulocytes imply hemolysis or bleeding. Low reticulocytes suggest production failure.", { ...S, chapter: "Anemia", section: "Workup" }),
  c("iron_deficiency_anemia", HEME, "Anemia", "Iron Deficiency Anemia", "Microcytic anemia from blood loss or inadequate intake with low ferritin and high TIBC.", "GI bleeding must be excluded in adult men and postmenopausal women. Iron repletion replaces stores.", { ...S, chapter: "Iron Deficiency", section: "Management" }),
  c("sickle_cell_disease", HEME, "Hemoglobinopathies", "Sickle Cell Disease", "Hemoglobin S polymerization causing vaso-occlusive pain, hemolysis, and organ damage.", "Hydroxyurea increases fetal hemoglobin. Splenic autoinfarction increases infection risk.", { ...S, chapter: "Sickle Cell", section: "Management" }),
  c("coagulopathy_and_dic", HEME, "Coagulation", "Coagulopathy and DIC", "Consumptive coagulopathy with thrombosis and bleeding in sepsis, malignancy, and obstetric catastrophes.", "DIC shows low fibrinogen and elevated D-dimer. Treat underlying trigger.", { ...S, chapter: "DIC", section: "Management" }),
  c("deep_vein_thrombosis_pe", HEME, "Thrombosis", "Deep Vein Thrombosis and PE", "Venous thromboembolism diagnosis with Wells criteria, compression ultrasound, and anticoagulation duration.", "Virchow triad explains pathogenesis. Cancer-associated thrombosis may need extended anticoagulation.", { ...S, chapter: "DVT", section: "Management" }),
  c("leukemia_overview", HEME, "Hematologic Malignancy", "Leukemia Overview", "Acute and chronic leukemias of lymphoid and myeloid lineages with cytogenetic risk stratification.", "AML shows Auer rods. CML has BCR-ABL and responds to tyrosine kinase inhibitors.", { ...S, chapter: "Leukemia", section: "Overview" }),
  c("lymphoma_overview", HEME, "Hematologic Malignancy", "Lymphoma Overview", "Hodgkin and non-Hodgkin lymphomas with nodal patterns, B symptoms, and chemoimmunotherapy regimens.", "Reed-Sternberg cells define Hodgkin lymphoma. DLBCL is common aggressive NHL.", { ...S, chapter: "Lymphoma", section: "Overview" }),
  c("solid_tumor_principles", HEME, "Oncology", "Solid Tumor Management Principles", "Surgery, radiation, systemic therapy, and staging informing multidisciplinary cancer care.", "TNM staging guides prognosis. Adjuvant therapy reduces recurrence after curative resection.", { ...S, chapter: "Oncology", section: "Principles" }),

  // Neurology (8)
  c("stroke_acute_management", NEURO, "Cerebrovascular Disease", "Acute Stroke Management", "Ischemic stroke thrombolysis and thrombectomy windows with blood pressure and glucose control.", "tPA within 4.5 hours for eligible ischemic stroke. NIHSS quantifies deficit severity.", { ...S, chapter: "Stroke", section: "Acute Management" }),
  c("seizure_and_epilepsy", NEURO, "Epilepsy", "Seizure and Epilepsy", "Provoked seizures versus epilepsy syndromes with antiepileptic drug selection by seizure type.", "Status epilepticus is neurologic emergency. Absence seizures show 3 Hz spike-wave on EEG.", { ...S, chapter: "Epilepsy", section: "Management" }),
  c("headache_red_flags", NEURO, "Headache", "Headache Red Flags and Secondary Causes", "Thunderclap, positional, and focal neurologic features prompting imaging for secondary headache.", "Subarachnoid hemorrhage presents sudden worst headache. Giant cell arteritis causes temporal headache in elderly.", { ...S, chapter: "Headache", section: "Red Flags" }),
  c("dementia_evaluation", NEURO, "Cognitive Disorders", "Dementia Evaluation", "Progressive cognitive decline workup distinguishing Alzheimer, vascular, Lewy body, and reversible causes.", "Mini-Mental State Exam screens cognition. B12, TSH, and neuroimaging exclude treatable causes.", { ...S, chapter: "Dementia", section: "Evaluation" }),
  c("parkinson_disease", NEURO, "Movement Disorders", "Parkinson Disease", "Bradykinesia, rigidity, tremor, and postural instability from nigrostriatal dopamine loss.", "Levodopa is most effective symptomatic therapy. Deep brain stimulation helps motor fluctuations.", { ...S, chapter: "Parkinson", section: "Management" }),
  c("multiple_sclerosis", NEURO, "Demyelinating Disease", "Multiple Sclerosis", "CNS demyelination with relapsing-remitting or progressive courses and MRI dissemination in time and space.", "Oligoclonal bands in CSF support diagnosis. Disease-modifying therapies reduce relapse rate.", { ...S, chapter: "Multiple Sclerosis", section: "Management" }),
  c("peripheral_neuropathy", NEURO, "Peripheral Nervous System", "Peripheral Neuropathy", "Length-dependent axonal and demyelinating neuropathies from diabetes, toxins, and nutritional deficiency.", "Stocking-glove sensory loss is typical. EMG and nerve conduction distinguish axonal from demyelinating.", { ...S, chapter: "Neuropathy", section: "Evaluation" }),
  c("meningitis_and_encephalitis", NEURO, "CNS Infections", "Meningitis and Encephalitis", "Acute CNS infection with lumbar puncture findings, empiric antibiotics, and antivirals when indicated.", "Bacterial meningitis shows low glucose and high protein in CSF. HSV encephalitis needs acyclovir promptly.", { ...S, chapter: "Meningitis", section: "Management" }),

  // Psychiatry & Behavioral Health (8)
  c("major_depressive_disorder", PSYCH, "Mood Disorders", "Major Depressive Disorder", "Persistent depressed mood and anhedonia with biologic and psychosocial treatments including SSRIs and CBT.", "Screen for suicide risk at every visit. Combined therapy and medication often most effective.", { ...S, chapter: "Depression", section: "Management" }),
  c("bipolar_disorder", PSYCH, "Mood Disorders", "Bipolar Disorder", "Manic and depressive episodes with mood stabilizers such as lithium and valproate preventing recurrence.", "Mania features elevated mood, decreased sleep, and risky behavior. Antidepressant monotherapy may trigger mania.", { ...S, chapter: "Bipolar", section: "Management" }),
  c("schizophrenia_spectrum", PSYCH, "Psychotic Disorders", "Schizophrenia Spectrum Disorders", "Positive and negative psychotic symptoms managed with antipsychotics and psychosocial rehabilitation.", "First episode psychosis warrants thorough medical workup. Clozapine for treatment-resistant schizophrenia.", { ...S, chapter: "Schizophrenia", section: "Management" }),
  c("anxiety_disorders", PSYCH, "Anxiety Disorders", "Anxiety Disorders", "GAD, panic disorder, and phobias treated with CBT, SSRIs, and short-term anxiolytics when appropriate.", "Panic attacks peak within minutes with somatic symptoms. Exposure therapy helps specific phobias.", { ...S, chapter: "Anxiety", section: "Management" }),
  c("substance_use_disorders", PSYCH, "Addiction Medicine", "Substance Use Disorders", "Alcohol, opioid, and stimulant use disorders with withdrawal management and maintenance therapies.", "Opioid withdrawal managed with buprenorphine or methadone. AUD responds to naltrexone and counseling.", { ...S, chapter: "Substance Use", section: "Management" }),
  c("eating_disorders", PSYCH, "Eating Disorders", "Eating Disorders", "Anorexia nervosa, bulimia nervosa, and binge-eating disorder with medical stabilization and psychotherapy.", "Anorexia has highest psychiatric mortality. Electrolyte abnormalities occur with purging behaviors.", { ...S, chapter: "Eating Disorders", section: "Management" }),
  c("personality_disorders_overview", PSYCH, "Personality Disorders", "Personality Disorders Overview", "Enduring maladaptive trait patterns including borderline, antisocial, and avoidant clusters.", "Borderline PD features unstable relationships and self-image. DBT is evidence-based for borderline PD.", { ...S, chapter: "Personality Disorders", section: "Overview" }),
  c("child_adolescent_psychiatry", PSYCH, "Developmental Psychiatry", "Child and Adolescent Psychiatry", "ADHD, autism spectrum, and conduct disorders with developmental-appropriate assessment and therapy.", "ADHD treated with stimulants and behavioral interventions. Autism diagnosis uses standardized criteria.", { ...S, chapter: "Child Psychiatry", section: "Overview" }),

  // Infectious Disease (8)
  c("sepsis_and_septic_shock", ID, "Critical Infections", "Sepsis and Septic Shock", "Dysregulated host response to infection with organ dysfunction requiring early antibiotics and resuscitation.", "qSOFA and SOFA scores identify severity. Hour-1 bundle emphasizes cultures and antibiotics.", { ...S, chapter: "Sepsis", section: "Management" }),
  c("hiv_aids_management", ID, "Retroviral Disease", "HIV/AIDS Management", "Antiretroviral therapy, opportunistic infection prophylaxis, and immune reconstitution monitoring.", "Undetectable viral load prevents sexual transmission. CD4 count guides OI prophylaxis thresholds.", { ...S, chapter: "HIV", section: "Management" }),
  c("tuberculosis", ID, "Mycobacterial Disease", "Tuberculosis", "Latent versus active TB with RIPE therapy and public health contact tracing.", "Latent TB treated with isoniazid or rifapentine regimens. MDR-TB requires prolonged multidrug therapy.", { ...S, chapter: "Tuberculosis", section: "Management" }),
  c("skin_soft_tissue_infections", ID, "Soft Tissue Infections", "Skin and Soft Tissue Infections", "Cellulitis, abscess, necrotizing fasciitis with drainage, antibiotics, and surgical debridement when urgent.", "Necrotizing infection needs immediate surgery. MRSA coverage considered in community abscess.", { ...S, chapter: "SSTI", section: "Management" }),
  c("meningitis_bacterial", ID, "CNS Infections", "Bacterial Meningitis", "Empiric cephalosporin plus vancomycin pending culture with dexamethasone in some cases.", "Neisseria meningitidis requires prophylaxis for close contacts. Petechial rash suggests meningococcemia.", { ...S, chapter: "Bacterial Meningitis", section: "Treatment" }),
  c("tick_borne_illnesses", ID, "Vector-Borne Disease", "Tick-Borne Illnesses", "Lyme disease, Rocky Mountain spotted fever, and ehrlichiosis with geographic and exposure history.", "Erythema migrans is pathognomonic early Lyme. Doxycycline treats many tick-borne rickettsial diseases.", { ...S, chapter: "Lyme Disease", section: "Management" }),
  c("travel_medicine_infections", ID, "Travel Medicine", "Travel-Related Infections", "Malaria, typhoid, and travelers diarrhea prevention and treatment by destination risk.", "Malaria prophylaxis depends on resistance patterns. Oral rehydration treats most travelers diarrhea.", { ...S, chapter: "Travel Medicine", section: "Infections" }),

  // Musculoskeletal & Rheumatology (8)
  c("osteoarthritis", MSK, "Degenerative Joint Disease", "Osteoarthritis", "Cartilage loss and osteophyte formation causing joint pain managed with exercise, NSAIDs, and injections.", "Weight loss reduces knee OA symptoms. Joint replacement for end-stage disease.", { ...S, chapter: "Osteoarthritis", section: "Management" }),
  c("rheumatoid_arthritis", MSK, "Inflammatory Arthritis", "Rheumatoid Arthritis", "Symmetric polyarthritis with erosions treated early with DMARDs and biologics to prevent joint damage.", "RF and anti-CCP support diagnosis. Methotrexate is anchor DMARD therapy.", { ...S, chapter: "Rheumatoid Arthritis", section: "Management" }),
  c("systemic_lupus_erythematosus", MSK, "Connective Tissue Disease", "Systemic Lupus Erythematosus", "Multisystem autoimmunity with malar rash, serositis, nephritis, and ANA-associated antibodies.", "Lupus nephritis requires immunosuppression. Hydroxychloroquine reduces flares and mortality.", { ...S, chapter: "SLE", section: "Management" }),
  c("gout_and_hyperuricemia", MSK, "Crystal Arthropathy", "Gout and Hyperuricemia", "Monosodium urate crystal arthritis with acute colchicine or NSAIDs and long-term urate lowering.", "Podagra is classic first attack. Allopurinol lowers uric acid preventing recurrent attacks.", { ...S, chapter: "Gout", section: "Management" }),
  c("vasculitis_syndromes", MSK, "Vasculitis", "Vasculitis Syndromes", "Small, medium, and large vessel vasculitides with organ-specific manifestations and immunosuppressive treatment.", "Giant cell arteritis causes headache and vision loss. ANCA-associated vasculitis affects kidneys and lungs.", { ...S, chapter: "Vasculitis", section: "Overview" }),
  c("back_pain_red_flags", MSK, "Spine", "Back Pain Red Flags", "Radiculopathy, cauda equina, infection, and malignancy features prompting urgent imaging.", "Cauda equina syndrome needs emergent MRI and decompression. Night pain suggests malignancy.", { ...S, chapter: "Back Pain", section: "Red Flags" }),
  c("osteoporosis_management", MSK, "Bone Health", "Osteoporosis Management", "DEXA screening, fracture risk assessment, and bisphosphonate or anabolic therapy.", "Fragility fractures occur from low trauma. Calcium and vitamin D support bone health.", { ...S, chapter: "Osteoporosis", section: "Management" }),

  // Dermatology (6)
  c("acne_and_rosacea", DERM, "Common Dermatology", "Acne and Rosacea", "Follicular inflammatory disorders managed with topical retinoids, antibiotics, and isotretinoin for severe acne.", "Isotretinoin requires pregnancy prevention. Rosacea triggers include alcohol and heat.", { ...S, chapter: "Acne", section: "Management" }),
  c("eczema_and_contact_dermatitis", DERM, "Inflammatory Dermatology", "Eczema and Contact Dermatitis", "Atopic dermatitis and allergen-triggered dermatitis with moisturization, steroids, and allergen avoidance.", "Patch testing identifies contact allergens. Atopic triad includes asthma and allergic rhinitis.", { ...S, chapter: "Dermatitis", section: "Management" }),
  c("psoriasis", DERM, "Inflammatory Dermatology", "Psoriasis", "Plaque psoriasis and variants with topical, phototherapy, and systemic immunomodulator options.", "Nail pitting and psoriatic arthritis associate with skin disease. Biologics target IL-17 and TNF.", { ...S, chapter: "Psoriasis", section: "Management" }),
  c("skin_cancer_screening", DERM, "Dermatologic Oncology", "Skin Cancer Screening", "ABCDE criteria for melanoma and management of basal and squamous cell carcinoma.", "Melanoma depth on Breslow scale guides prognosis. Wide local excision is primary treatment.", { ...S, chapter: "Skin Cancer", section: "Screening" }),
  c("drug_eruptions", DERM, "Adverse Drug Reactions", "Drug Eruptions", "Morbilliform rash, Stevens-Johnson syndrome, and DRESS from medication hypersensitivity.", "SJS/TEN requires drug cessation and supportive burn-unit care. High mortality with extensive detachment.", { ...S, chapter: "Drug Eruptions", section: "Severe Reactions" }),
  c("bacterial_fungal_skin_infections", DERM, "Infectious Dermatology", "Bacterial and Fungal Skin Infections", "Impetigo, cellulitis, tinea, and candidiasis with topical and systemic antimicrobial therapy.", "Ringworm shows annular scaly plaques. Oral antifungals treat onychomycosis.", { ...S, chapter: "Skin Infections", section: "Management" }),

  // Obstetrics & Gynecology (7)
  c("prenatal_care_and_screening", OBGYN, "Obstetrics", "Prenatal Care and Screening", "Trimester visits, ultrasound anatomy survey, and screening for aneuploidy and gestational diabetes.", "Folic acid prevents neural tube defects. Rh incompatibility managed with anti-D immunoglobulin.", { ...S, chapter: "Prenatal Care", section: "Screening" }),
  c("labor_and_delivery", OBGYN, "Obstetrics", "Labor and Delivery", "Stages of labor, fetal monitoring, dystocia management, and operative delivery indications.", "Active labor progresses with cervical change. Category II tracing warrants close evaluation.", { ...S, chapter: "Labor", section: "Management" }),
  c("postpartum_complications", OBGYN, "Obstetrics", "Postpartum Complications", "Hemorrhage, infection, depression, and thromboembolism in the postpartum period.", "Uterine atony is leading cause of postpartum hemorrhage. Oxytocin and massage are first-line.", { ...S, chapter: "Postpartum", section: "Complications" }),
  c("contraception_methods", OBGYN, "Gynecology", "Contraception Methods", "Hormonal, barrier, intrauterine, and permanent contraception with efficacy and contraindications.", "Copper IUD is highly effective nonhormonal option. Estrogen contraindicated in thrombophilia.", { ...S, chapter: "Contraception", section: "Methods" }),
  c("abnormal_uterine_bleeding", OBGYN, "Gynecology", "Abnormal Uterine Bleeding", "PALM-COEIN classification guiding structural versus hormonal evaluation and treatment.", "Fibroids and polyps are structural causes. Anovulatory bleeding common in PCOS.", { ...S, chapter: "AUB", section: "Evaluation" }),
  c("pelvic_inflammatory_disease", OBGYN, "Gynecologic Infections", "Pelvic Inflammatory Disease", "Ascending infection causing salpingitis with antibiotic regimens covering gonorrhea and chlamydia.", "PID risks ectopic pregnancy and infertility. Partner treatment prevents reinfection.", { ...S, chapter: "PID", section: "Management" }),
  c("cervical_cancer_prevention", OBGYN, "Gynecologic Oncology", "Cervical Cancer Prevention", "HPV vaccination, Pap and HPV co-testing, and colposcopy for precancerous lesions.", "HPV 16 and 18 are high-risk oncogenic types. CIN management depends on grade and age.", { ...S, chapter: "Cervical Cancer", section: "Prevention" }),

  // Surgery & Perioperative Care (13)
  c("preoperative_assessment", SURG, "Perioperative Medicine", "Preoperative Assessment", "Cardiopulmonary risk stratification, medication management, and fasting guidelines before surgery.", "RCRI estimates cardiac risk. Beta-blockers continued perioperatively when already indicated.", { ...S, chapter: "Preoperative", section: "Assessment" }),
  c("postoperative_fever", SURG, "Perioperative Complications", "Postoperative Fever", "Timing-based differential including atelectasis, wound infection, UTI, DVT, and drug fever.", "Wind-water-wound-walk-wonder mnemonic organizes causes by postoperative day.", { ...S, chapter: "Postoperative Fever", section: "Causes" }),
  c("acute_abdomen_evaluation", SURG, "Acute Care Surgery", "Acute Abdomen Evaluation", "Surgical versus medical abdominal pain with imaging, labs, and operative indications.", "Peritonitis suggests surgical emergency. Free air on imaging indicates perforation.", { ...S, chapter: "Acute Abdomen", section: "Evaluation" }),
  c("appendicitis", SURG, "Acute Care Surgery", "Appendicitis", "Inflamed appendix presenting with periumbilical pain migrating to RLQ requiring appendectomy.", "Alvarado score supports diagnosis. Perforation increases morbidity especially in children.", { ...S, chapter: "Appendicitis", section: "Management" }),
  c("cholecystitis_and_cholelithiasis", SURG, "Hepatobiliary Surgery", "Cholecystitis and Cholelithiasis", "Gallstone disease with biliary colic versus acute cholecystitis treated with cholecystectomy.", "Murphy sign suggests cholecystitis. CBD stones may cause cholangitis and pancreatitis.", { ...S, chapter: "Cholecystitis", section: "Management" }),
  c("bowel_obstruction", SURG, "GI Surgery", "Bowel Obstruction", "Small and large bowel obstruction from adhesions, hernia, or malignancy with nasogastric decompression and surgery.", "Air-fluid levels on upright abdominal film. Closed-loop obstruction risks strangulation.", { ...S, chapter: "Bowel Obstruction", section: "Management" }),
  c("hernia_repair_principles", SURG, "Abdominal Wall", "Hernia Repair Principles", "Inguinal and femoral hernias with reducibility, incarceration risk, and mesh repair techniques.", "Indirect inguinal hernia passes through internal ring. Femoral hernias have high incarceration risk.", { ...S, chapter: "Hernia", section: "Repair" }),
  c("trauma_primary_survey", SURG, "Trauma Surgery", "Trauma Primary Survey", "ABCDE approach stabilizing airway, breathing, circulation, disability, and exposure in injured patients.", "Massive transfusion protocol for hemorrhagic shock. FAST exam detects intraperitoneal blood.", { ...S, chapter: "Trauma", section: "Primary Survey" }),
  c("burns_management", SURG, "Trauma Surgery", "Burns Management", "TBSA estimation, fluid resuscitation, eschar care, and referral criteria for burn centers.", "Parkland formula guides initial fluids. Circumferential burns may need escharotomy.", { ...S, chapter: "Burns", section: "Management" }),
  c("wound_healing_surgical", SURG, "Surgical Principles", "Surgical Wound Healing", "Primary, secondary, and tertiary closure with factors impairing healing including diabetes and infection.", "Tension-free closure reduces dehiscence. Prophylactic antibiotics indicated for dirty-contaminated cases.", { ...S, chapter: "Wound Care", section: "Healing" }),
  c("breast_cancer_surgery", SURG, "Surgical Oncology", "Breast Cancer Surgery", "Lumpectomy versus mastectomy with sentinel lymph node biopsy and adjuvant therapy planning.", "Margins clear of tumor required for breast conservation. SLNB avoids full axillary dissection when negative.", { ...S, chapter: "Breast Cancer", section: "Surgery" }),
  c("thyroid_surgery_complications", SURG, "Endocrine Surgery", "Thyroid Surgery Complications", "Recurrent laryngeal nerve injury, hypocalcemia from parathyroid damage, and hematoma airway compromise.", "Hoarseness suggests nerve injury. Perioperative calcium monitoring detects hypoparathyroidism.", { ...S, chapter: "Thyroid Surgery", section: "Complications" }),
  c("anesthesia_basics", SURG, "Anesthesiology", "Anesthesia Basics", "General, regional, and local anesthesia with airway management and malignant hyperthermia awareness.", "Spinal anesthesia for lower abdominal surgery. Succinylcholine contraindicated in malignant hyperthermia susceptibility.", { ...S, chapter: "Anesthesia", section: "Overview" }),
];
