import type { MedL3Spec } from "./_medicineL3Generator.js";

const GROSS = "Gross Anatomy";
const HIST = "Histology & Cell Ultrastructure";
const EMBRYO = "Embryology & Development";
const PHYS = "Physiology";
const BIOCHEM = "Biochemistry & Metabolism";
const PHARM = "Pharmacology";
const PATH = "Pathology";
const MICRO = "Microbiology & Infectious Disease";
const IMMUNO = "Immunology";
const NEURO = "Neuroscience";
const GENETICS = "Genetics & Molecular Medicine";
const BEHAV = "Behavioral Science & Epidemiology";

const O = { source: "OpenStax Anatomy and Physiology 2e" };
const S = { source: "NCBI StatPearls" };
const T = {
  source: "No open-source reference identified — requires manual citation",
  chapter: "TBD",
  section: "TBD",
};

function c(
  shortName: string,
  l2: string,
  cluster: string,
  title: string,
  definition: string,
  summary: string,
  source: { source: string; chapter?: string; section?: string },
  prerequisites?: string[],
  unlocks?: string[],
): MedL3Spec {
  return {
    shortName,
    l2,
    cluster,
    title,
    definition,
    summary,
    prerequisites,
    unlocks,
    source: {
      source: source.source,
      chapter: source.chapter ?? "TBD",
      section: source.section ?? "TBD",
    },
  };
}

export const PRECLINICAL_SPECS: MedL3Spec[] = [
  // Gross Anatomy (8)
  c("body_planes_and_regions", GROSS, "Anatomic Orientation", "Body Planes and Regions", "Standard anatomic planes (sagittal, coronal, transverse) and regional nomenclature used to describe structure location.", "Planes and directional terms localize injuries and surgical approaches. Regional anatomy groups structures for clinical examination.", { ...O, chapter: "1", section: "1.6" }),
  c("musculoskeletal_system_overview", GROSS, "Musculoskeletal", "Musculoskeletal System Overview", "Bones, joints, muscles, and connective tissues that provide support, protection, and movement.", "Musculoskeletal anatomy links palpable landmarks to underlying pathology. Origin-insertion relationships predict movement deficits.", { ...O, chapter: "6", section: "6.1" }),
  c("cardiovascular_anatomy_heart_great_vessels", GROSS, "Cardiovascular", "Heart and Great Vessels Anatomy", "Chambers, valves, coronary circulation, and major arterial-venous connections of the thoracic cardiovascular system.", "Cardiac chamber anatomy explains murmur locations and conduction pathways. Coronary dominance affects ischemia patterns.", { ...O, chapter: "19", section: "19.1" }),
  c("respiratory_tract_anatomy", GROSS, "Respiratory", "Respiratory Tract Anatomy", "Conducting and respiratory zones from nose to alveoli including pleura and mediastinal relations.", "Segmental bronchial anatomy guides localization of infiltrates. Pleural spaces explain pneumothorax and effusion mechanics.", { ...O, chapter: "22", section: "22.1" }),
  c("gastrointestinal_tract_anatomy", GROSS, "Gastrointestinal", "Gastrointestinal Tract Anatomy", "Oral cavity through anal canal including foregut-midgut-hindgut derivatives and associated vasculature.", "GI segmental blood supply predicts ischemia territories. Portosystemic anastomoses explain variceal bleeding.", { ...O, chapter: "23", section: "23.1" }),
  c("renal_and_urinary_tract_anatomy", GROSS, "Renal", "Renal and Urinary Tract Anatomy", "Kidneys, ureters, bladder, and urethra with segmental innervation and retroperitoneal relationships.", "Renal segmental anatomy informs partial nephrectomy and stone management. Ureteric course explains referred pain.", { ...O, chapter: "25", section: "25.1" }),
  c("nervous_system_gross_organization", GROSS, "Nervous System", "Nervous System Gross Organization", "Central and peripheral nervous system divisions, meninges, ventricles, and major fiber tracts.", "Gross neuroanatomy localizes lesions by motor-sensory level. Meningeal layers explain epidural versus subdural collections.", { ...O, chapter: "13", section: "13.1" }),
  c("pelvic_and_reproductive_anatomy", GROSS, "Reproductive", "Pelvic and Reproductive Anatomy", "Pelvic viscera, perineum, and male-female reproductive organs with ligamentous support.", "Pelvic anatomy explains obstetric injury patterns and hernia types. Urogenital diaphragm supports continence mechanisms.", { ...O, chapter: "27", section: "27.1" }),

  // Histology (7)
  c("epithelial_tissue_types", HIST, "Epithelial Tissue", "Epithelial Tissue Types", "Simple and stratified epithelia classified by cell shape and layering with specialized surface modifications.", "Epithelial classification predicts carcinoma origin and barrier function. Cilia and microvilli reflect organ-specific roles.", { ...O, chapter: "4", section: "4.2" }),
  c("connective_tissue_matrix", HIST, "Connective Tissue", "Connective Tissue Matrix", "Extracellular matrix components including collagen, elastin, and ground substance produced by fibroblasts and related cells.", "Matrix composition determines tissue strength and repair. Collagen types correlate with scar formation and heritable disorders.", { ...O, chapter: "4", section: "4.3" }),
  c("muscle_tissue_histology", HIST, "Muscle Tissue", "Muscle Tissue Histology", "Skeletal, cardiac, and smooth muscle microscopic structure including sarcomeres and intercalated discs.", "Muscle histology distinguishes rhabdomyolysis from cardiomyopathy. Intercalated discs enable coordinated cardiac contraction.", { ...O, chapter: "4", section: "4.4" }),
  c("nervous_tissue_histology", HIST, "Nervous Tissue", "Nervous Tissue Histology", "Neurons, glia, and myelin with regional cytoarchitecture of gray and white matter.", "Glial proportions explain glioma categories. Myelin histology underlies demyelinating disease pathology.", { ...O, chapter: "4", section: "4.5" }),
  c("cell_organelles_ultrastructure", HIST, "Cell Ultrastructure", "Cell Organelles and Ultrastructure", "Membrane-bound organelles and cytoskeletal elements visible at electron microscopic resolution.", "Organelle defects cause inherited metabolic disease. Mitochondrial ultrastructure links to oxidative phosphorylation capacity.", { ...O, chapter: "3", section: "3.2" }),
  c("membrane_transport_ultrastructure", HIST, "Cell Ultrastructure", "Membrane Transport Ultrastructure", "Channel, carrier, and vesicular transport machinery at the plasma membrane and organelle membranes.", "Transport protein localization explains secretory versus absorptive epithelia. Endocytosis pathways mediate receptor turnover.", { ...O, chapter: "3", section: "3.4" }),
  c("cell_junctions_and_adhesion", HIST, "Cell Junctions", "Cell Junctions and Adhesion", "Tight, adherens, desmosomal, and gap junctions organizing tissue barriers and intercellular communication.", "Tight junction integrity maintains epithelial polarity. Desmosome autoimmunity causes blistering skin disease.", { ...O, chapter: "4", section: "4.2" }),

  // Embryology (7)
  c("germ_layer_derivatives", EMBRYO, "Germ Layers", "Germ Layer Derivatives", "Ectoderm, mesoderm, and endoderm giving rise to organ systems during early organogenesis.", "Germ layer origin predicts congenital malformation patterns. Neural crest derivatives span diverse tissues.", { ...O, chapter: "28", section: "28.2" }),
  c("neurulation_and_neural_tube", EMBRYO, "Neural Development", "Neurulation and Neural Tube Formation", "Folding of neural plate into neural tube with closure defects producing spina bifida and anencephaly.", "Neural tube closure timing explains folic acid prevention. Level of defect correlates with neurologic deficit.", { ...O, chapter: "28", section: "28.3" }),
  c("cardiovascular_embryology", EMBRYO, "Cardiovascular Development", "Cardiovascular Embryology", "Heart tube looping, septation, and outflow tract remodeling forming four-chamber circulation.", "Conotruncal anomalies link to neural crest migration. Septation defects explain left-to-right shunts at birth.", { ...O, chapter: "28", section: "28.4" }),
  c("respiratory_embryology", EMBRYO, "Respiratory Development", "Respiratory Embryology", "Lung bud branching, alveolarization, and surfactant-producing cell differentiation.", "Alveolar development continues postnatally. Surfactant deficiency causes neonatal respiratory distress syndrome.", { ...O, chapter: "28", section: "28.5" }),
  c("gastrointestinal_embryology", EMBRYO, "GI Development", "Gastrointestinal Embryology", "Foregut rotation, midgut herniation, and hindgut partitioning with vitelline duct regression.", "Rotation errors cause volvulus and malrotation. Meckel diverticulum reflects persistent vitelline duct.", { ...O, chapter: "28", section: "28.6" }),
  c("urogenital_embryology", EMBRYO, "Urogenital Development", "Urogenital Embryology", "Intermediate mesoderm forming kidneys, gonads, and internal-external genitalia with duct fusion events.", "Müllerian and Wolffian duct fate depends on hormones. Renal ascent explains ectopic kidney locations.", { ...O, chapter: "28", section: "28.7" }),
  c("fetal_circulation_and_transition", EMBRYO, "Fetal Circulation", "Fetal Circulation and Neonatal Transition", "Placental gas exchange, shunts (foramen ovale, ductus arteriosus), and postnatal closure.", "Persistent fetal shunts cause cyanotic disease. Ductus-dependent lesions require prostaglandin management.", { ...O, chapter: "28", section: "28.4" }),

  // Physiology (18) — high Step 1 yield
  c("cell_membrane_resting_potential", PHYS, "Electrophysiology", "Cell Membrane Resting Potential", "Ion gradients and selective permeability establishing negative interior voltage in excitable and non-excitable cells.", "Resting potential sets the threshold for excitation. Na-K-ATPase maintains gradients consumed during signaling.", { ...O, chapter: "12", section: "12.2" }),
  c("cardiac_membrane_potential", PHYS, "Cardiac Electrophysiology", "Cardiac Membrane Potential", "Atrial and ventricular myocyte ion fluxes producing resting potential, phase 0–4 currents, and pacemaker automaticity.", "Cardiac action potential phases explain antiarrhythmic drug classes. Pacemaker cells drive intrinsic heart rate.", { ...O, chapter: "19", section: "19.2" }, undefined, ["spine_biology_l3_action_potential"]),
  c("cardiac_output_and_starling_law", PHYS, "Cardiovascular Physiology", "Cardiac Output and Frank-Starling Law", "Stroke volume and heart rate determining cardiac output with preload-dependent sarcomere length-tension relationships.", "Starling mechanism matches venous return to output. Heart failure shifts the ventricular function curve.", { ...O, chapter: "19", section: "19.3" }),
  c("systemic_and_pulmonary_circulation", PHYS, "Cardiovascular Physiology", "Systemic and Pulmonary Circulation", "Pressure-flow relationships, vascular resistance, and compliance in parallel and series circulations.", "Pulmonary versus systemic resistance explains shunt physiology. Vascular compliance buffers pulsatile flow.", { ...O, chapter: "19", section: "19.4" }),
  c("blood_pressure_regulation", PHYS, "Cardiovascular Physiology", "Blood Pressure Regulation", "Baroreceptor reflex, renin-angiotensin-aldosterone system, and autonomic control of vascular tone.", "Baroreceptor resetting occurs in chronic hypertension. RAAS integrates renal and vascular responses.", { ...O, chapter: "20", section: "20.4" }),
  c("respiratory_mechanics_and_compliance", PHYS, "Respiratory Physiology", "Respiratory Mechanics and Compliance", "Lung and chest wall elastic recoil, airway resistance, and work of breathing.", "Compliance changes in ARDS and emphysema alter ventilation. Airway resistance rises in bronchospasm.", { ...O, chapter: "22", section: "22.3" }),
  c("gas_exchange_and_ventilation_perfusion", PHYS, "Respiratory Physiology", "Gas Exchange and Ventilation-Perfusion Matching", "Oxygen and carbon dioxide diffusion across alveolar-capillary membrane with regional V/Q ratios.", "V/Q mismatch causes hypoxemia. Dead space and shunt physiology explain A-a gradient abnormalities.", { ...O, chapter: "22", section: "22.4" }),
  c("oxygen_hemoglobin_dissociation", PHYS, "Respiratory Physiology", "Oxygen-Hemoglobin Dissociation", "Cooperative hemoglobin binding modulated by pH, temperature, and 2,3-BPG shifting the dissociation curve.", "Right shift enhances tissue unloading in acidosis and exercise. Carbon monoxide shifts curve left and reduces capacity.", { ...O, chapter: "22", section: "22.5" }),
  c("renal_filtration_and_gfr", PHYS, "Renal Physiology", "Renal Filtration and GFR", "Glomerular ultrafiltration driven by Starling forces with autoregulation of renal blood flow.", "GFR estimation guides drug dosing and CKD staging. Autoregulation fails in severe hypotension.", { ...O, chapter: "25", section: "25.3" }),
  c("tubular_reabsorption_and_secretion", PHYS, "Renal Physiology", "Tubular Reabsorption and Secretion", "Segment-specific transport reclaiming water, electrolytes, and nutrients while secreting acids and organic solutes.", "Proximal tubule reabsorbs bulk filtrate. Loop diuretics act on ascending limb Na-K-2Cl cotransport.", { ...O, chapter: "25", section: "25.4" }),
  c("acid_base_balance_renal", PHYS, "Renal Physiology", "Renal Acid-Base Balance", "Bicarbonate reabsorption, ammonium excretion, and titratable acid eliminating nonvolatile acid load.", "Renal compensation for respiratory disorders is slower but sustained. Distal RTA reflects specific transporter defects.", { ...O, chapter: "25", section: "25.5" }),
  c("gi_motility_and_secretion", PHYS, "GI Physiology", "GI Motility and Secretion", "Peristalsis, sphincter tone, and exocrine-endocrine secretions coordinated by neural and hormonal signals.", "Migrating motor complexes clear fasting stomach. Secretin and CCK orchestrate digestive enzyme release.", { ...O, chapter: "23", section: "23.3" }),
  c("nutrient_absorption_physiology", PHYS, "GI Physiology", "Nutrient Absorption Physiology", "Carbohydrate, protein, and lipid digestion products absorbed via transporters and chylomicron formation.", "Lactase deficiency causes osmotic diarrhea. Bile salts are essential for fat-soluble vitamin absorption.", { ...O, chapter: "23", section: "23.4" }),
  c("endocrine_feedback_axes", PHYS, "Endocrine Physiology", "Endocrine Feedback Axes", "Hypothalamic-pituitary-target gland loops maintaining hormone concentrations within set points.", "Negative feedback explains suppression tests. Primary versus secondary disorders differ by hormone levels.", { ...O, chapter: "17", section: "17.2" }),
  c("glucose_homeostasis_insulin_glucagon", PHYS, "Endocrine Physiology", "Glucose Homeostasis: Insulin and Glucagon", "Pancreatic islet hormones regulating hepatic glucose production and peripheral uptake.", "Insulin deficiency causes hyperglycemia and ketogenesis. Glucagon rescues hypoglycemia in alpha-cell function.", { ...O, chapter: "17", section: "17.4" }),
  c("thyroid_hormone_synthesis_and_action", PHYS, "Endocrine Physiology", "Thyroid Hormone Synthesis and Action", "Iodine trapping, organification, coupling, and nuclear receptor-mediated metabolic effects of T3 and T4.", "TSH drives thyroid growth and hormone release. T3 potentiates beta-adrenergic sensitivity.", { ...O, chapter: "17", section: "17.5" }),
  c("skeletal_muscle_contraction", PHYS, "Musculoskeletal Physiology", "Skeletal Muscle Contraction", "Excitation-contraction coupling via calcium release, troponin-tropomyosin regulation, and cross-bridge cycling.", "Muscle fiber types differ in oxidative capacity. Rigor mortis reflects persistent actin-myosin binding.", { ...O, chapter: "10", section: "10.3" }),
  c("synaptic_transmission_physiology", PHYS, "Neurophysiology", "Synaptic Transmission Physiology", "Presynaptic vesicle release, postsynaptic receptor activation, and termination of neurotransmitter signaling.", "EPSPs and IPSPs integrate to threshold. Reuptake inhibitors prolong synaptic neurotransmitter action.", { ...O, chapter: "12", section: "12.5" }),

  // Biochemistry & Metabolism (9)
  c("enzyme_kinetics_michaelis_menten", BIOCHEM, "Enzyme Kinetics", "Enzyme Kinetics and Michaelis-Menten", "Hyperbolic rate-substrate relationships characterized by Vmax and Km reflecting enzyme saturation.", "Km approximates substrate affinity. Competitive inhibitors increase apparent Km without changing Vmax.", { ...O, chapter: "24", section: "24.2" }),
  c("glycolysis_and_gluconeogenesis", BIOCHEM, "Carbohydrate Metabolism", "Glycolysis and Gluconeogenesis", "Cytoplasmic pathways converting glucose to pyruvate and reversing net synthesis during fasting.", "Irreversible steps are regulated by kinases and phosphatases. Pyruvate carboxylase links to TCA cycle.", { ...O, chapter: "24", section: "24.3" }),
  c("tca_cycle_and_electron_transport", BIOCHEM, "Energy Metabolism", "TCA Cycle and Electron Transport", "Mitochondrial oxidation of acetyl-CoA with NADH and FADH2 driving oxidative phosphorylation.", "ETC inhibitors and uncouplers reduce ATP yield. Inherited ETC defects cause lactic acidosis.", { ...O, chapter: "24", section: "24.4" }),
  c("fatty_acid_synthesis_and_oxidation", BIOCHEM, "Lipid Metabolism", "Fatty Acid Synthesis and Beta-Oxidation", "Cytosolic lipogenesis versus mitochondrial beta-oxidation supplying acetyl-CoA and ketone bodies.", "Carnitine shuttle defects impair long-chain oxidation. Ketogenesis rises during prolonged fasting.", { ...O, chapter: "24", section: "24.5" }),
  c("amino_acid_metabolism_and_urea_cycle", BIOCHEM, "Protein Metabolism", "Amino Acid Metabolism and Urea Cycle", "Transamination, deamination, and hepatic urea synthesis disposing of nitrogen.", "Hyperammonemia from urea cycle defects causes encephalopathy. Maple syrup urine disease blocks branched-chain degradation.", { ...O, chapter: "24", section: "24.6" }),
  c("nucleotide_synthesis_and_purine_salvage", BIOCHEM, "Nucleotide Metabolism", "Nucleotide Synthesis and Purine Salvage", "De novo and salvage pathways for purines and pyrimidines with feedback inhibition.", "HGPRT deficiency causes Lesch-Nyhan syndrome. Antimetabolites target nucleotide synthesis in cancer.", { ...O, chapter: "24", section: "24.7" }),
  c("heme_synthesis_and_porphyrias", BIOCHEM, "Heme Metabolism", "Heme Synthesis and Porphyrias", "Mitochondrial and cytosolic steps forming protoporphyrin IX and heme with enzymatic block porphyrias.", "ALA and PBG accumulate in acute intermittent porphyria. Lead inhibits ALA dehydratase and ferrochelatase.", { ...O, chapter: "24", section: "24.8" }),
  c("vitamin_cofactors_and_deficiencies", BIOCHEM, "Vitamins", "Vitamin Cofactors and Deficiencies", "Water- and fat-soluble vitamins serving as coenzymes or antioxidants with deficiency syndromes.", "Thiamine deficiency causes Wernicke encephalopathy. Vitamin D regulates calcium and phosphate homeostasis.", { ...S, chapter: "Vitamins", section: "Overview" }),
  c("collagen_synthesis_and_disorders", BIOCHEM, "Structural Proteins", "Collagen Synthesis and Disorders", "Post-translational hydroxylation, glycosylation, and cross-linking of procollagen with heritable defects.", "Osteogenesis imperfecta reflects type I collagen defects. Ehlers-Danlos syndromes involve collagen processing.", { ...S, chapter: "Collagen", section: "Structure" }),

  // Pharmacology (18) — high Step 1 yield
  c("pharmacokinetics_absorption_distribution", PHARM, "Pharmacokinetics", "Drug Absorption and Distribution", "Routes of administration, bioavailability, and tissue partitioning governed by physicochemical properties.", "First-pass metabolism lowers oral bioavailability. Lipophilicity and protein binding affect distribution.", { ...S, chapter: "Pharmacokinetics", section: "Absorption" }),
  c("volume_of_distribution", PHARM, "Pharmacokinetics", "Volume of Distribution", "Apparent compartment volume relating total body drug amount to plasma concentration after distribution.", "Large Vd suggests extensive tissue binding. Vd informs loading dose calculations.", { ...S, chapter: "Pharmacokinetics", section: "Volume of Distribution" }, undefined, ["spine_medicine_preclinical_l3_drug_elimination_kinetics"]),
  c("drug_elimination_kinetics", PHARM, "Pharmacokinetics", "Drug Elimination Kinetics", "First-order clearance processes removing drug proportional to plasma concentration with characteristic half-life.", "Most drugs follow first-order elimination. Clearance and half-life determine dosing intervals.", { ...S, chapter: "Pharmacokinetics", section: "Elimination" }, ["spine_medicine_preclinical_l3_volume_of_distribution", "spine_mathematics_l3_exponential_decay"], ["spine_medicine_preclinical_l3_steady_state_concentration"]),
  c("steady_state_concentration", PHARM, "Pharmacokinetics", "Steady-State Drug Concentration", "Plateau plasma level reached when dosing rate equals elimination rate, approximated after five half-lives.", "Steady state depends on dose, interval, and half-life. Loading doses accelerate therapeutic levels.", { ...S, chapter: "Pharmacokinetics", section: "Steady State" }, ["spine_medicine_preclinical_l3_drug_elimination_kinetics"]),
  c("drug_metabolism_cytochrome_p450", PHARM, "Drug Metabolism", "Cytochrome P450 Drug Metabolism", "Hepatic phase I oxidation-reduction reactions primarily catalyzed by CYP isoforms with inducible activity.", "CYP induction accelerates metabolism of other substrates. Genetic polymorphisms alter drug levels.", { ...S, chapter: "Pharmacology", section: "Drug Metabolism" }),
  c("renal_drug_elimination", PHARM, "Drug Elimination", "Renal Drug Elimination", "Glomerular filtration, tubular secretion, and reabsorption determining renal clearance.", "Dose adjustment required in CKD for renally cleared drugs. Probenecid blocks tubular secretion.", { ...S, chapter: "Pharmacokinetics", section: "Renal Clearance" }),
  c("receptor_pharmacodynamics", PHARM, "Pharmacodynamics", "Receptor Pharmacodynamics", "Agonist and antagonist binding producing graded and quantal dose-response relationships.", "Efficacy versus potency distinguish full and partial agonists. Competitive antagonism shifts dose-response right.", { ...S, chapter: "Pharmacodynamics", section: "Receptors" }),
  c("autonomic_pharmacology_cholinergic", PHARM, "Autonomic Pharmacology", "Cholinergic Pharmacology", "Drugs modulating acetylcholine synthesis, release, receptor binding, and acetylcholinesterase activity.", "Muscarinic agonists increase secretions and motility. Anticholinesterases treat myasthenia but risk cholinergic crisis.", { ...S, chapter: "Autonomic", section: "Cholinergic" }),
  c("autonomic_pharmacology_adrenergic", PHARM, "Autonomic Pharmacology", "Adrenergic Pharmacology", "Alpha and beta receptor agonists and antagonists affecting cardiovascular and bronchial tone.", "Beta-blockers reduce heart rate and contractility. Alpha-1 blockade causes orthostatic hypotension.", { ...S, chapter: "Autonomic", section: "Adrenergic" }),
  c("antiarrhythmic_drug_classes", PHARM, "Cardiovascular Pharmacology", "Antiarrhythmic Drug Classes", "Vaughan Williams classification targeting sodium, beta, potassium, and calcium channels in cardiac tissue.", "Class I agents block Na channels prolonging depolarization. Class III prolong repolarization via K blockade.", { ...S, chapter: "Cardiovascular", section: "Antiarrhythmics" }),
  c("antihypertensive_drug_mechanisms", PHARM, "Cardiovascular Pharmacology", "Antihypertensive Drug Mechanisms", "Agents lowering blood pressure via diuresis, RAAS blockade, vasodilation, or cardiac depression.", "ACE inhibitors cause cough and angioedema. Thiazides are first-line in many hypertension guidelines.", { ...S, chapter: "Cardiovascular", section: "Antihypertensives" }),
  c("antimicrobial_mechanisms_resistance", PHARM, "Antimicrobial Pharmacology", "Antimicrobial Mechanisms and Resistance", "Drug classes inhibiting cell wall, protein, nucleic acid, or folate synthesis with resistance mechanisms.", "Beta-lactams require active cell wall synthesis. Efflux pumps and modifying enzymes confer resistance.", { ...S, chapter: "Antimicrobials", section: "Mechanisms" }),
  c("chemotherapy_cell_cycle_specificity", PHARM, "Oncology Pharmacology", "Chemotherapy Cell-Cycle Specificity", "Antineoplastic agents targeting S, M, or G phases versus cycle-nonspecific DNA alkylators.", "Methotrexate is S-phase specific. Combination regimens balance efficacy and overlapping toxicity.", { ...S, chapter: "Chemotherapy", section: "Cell Cycle" }),
  c("nsaid_and_opioid_pharmacology", PHARM, "Analgesic Pharmacology", "NSAID and Opioid Pharmacology", "COX inhibition for inflammation and analgesia versus mu-receptor opioid effects and dependence.", "NSAIDs risk GI ulceration and renal impairment. Opioids cause respiratory depression and constipation.", { ...S, chapter: "Analgesics", section: "NSAIDs and Opioids" }),
  c("anticoagulant_and_antiplatelet_agents", PHARM, "Hematologic Pharmacology", "Anticoagulant and Antiplatelet Agents", "Warfarin, heparin, direct oral anticoagulants, and antiplatelet drugs interrupting clotting cascades.", "Warfarin requires INR monitoring and vitamin K reversal. Heparin-induced thrombocytopenia is an immune complication.", { ...S, chapter: "Anticoagulation", section: "Agents" }),
  c("cns_pharmacology_sedatives_antidepressants", PHARM, "CNS Pharmacology", "CNS Sedatives and Antidepressants", "Benzodiazepines, barbiturates, SSRIs, and related agents modulating inhibitory and monoaminergic signaling.", "Benzodiazepines enhance GABA-A chloride influx. SSRIs increase synaptic serotonin via reuptake blockade.", { ...S, chapter: "CNS", section: "Psychotropics" }),
  c("diabetes_pharmacotherapy", PHARM, "Endocrine Pharmacology", "Diabetes Pharmacotherapy", "Insulin preparations and oral agents increasing secretion, sensitivity, or reducing hepatic glucose output.", "Metformin lowers hepatic gluconeogenesis. Sulfonylureas stimulate insulin release risking hypoglycemia.", { ...S, chapter: "Endocrine", section: "Diabetes Drugs" }),
  c("toxicology_antidotes", PHARM, "Toxicology", "Toxicology and Antidotes", "Recognition of common poisonings and specific antidotes or supportive therapies reversing toxicity.", "N-acetylcysteine treats acetaminophen overdose. Opioid reversal uses naloxone.", { ...S, chapter: "Toxicology", section: "Antidotes" }),

  // Pathology (18) — high Step 1 yield
  c("cell_injury_and_adaptation", PATH, "General Pathology", "Cell Injury and Adaptation", "Reversible injury, necrosis, apoptosis, and hypertrophy-atrophy-metaplasia responses to stress.", "Ischemia causes ATP depletion and reversible swelling before necrosis. Apoptosis is programmed and regulated.", { ...S, chapter: "Cell Injury", section: "Overview" }),
  c("inflammation_acute_and_chronic", PATH, "Inflammation", "Acute and Chronic Inflammation", "Vascular and cellular events with neutrophil and macrophage recruitment resolving or persisting as chronicity.", "Acute inflammation features exudate and neutrophils. Granulomas characterize chronic immune activation.", { ...S, chapter: "Inflammation", section: "Types" }),
  c("wound_healing_and_repair", PATH, "Tissue Repair", "Wound Healing and Repair", "Hemostasis, inflammation, proliferation, and remodeling phases restoring tissue integrity.", "Primary intention minimizes scar. Keloids reflect excessive collagen deposition in susceptible individuals.", { ...S, chapter: "Wound Healing", section: "Phases" }),
  c("neoplasia_benign_malignant", PATH, "Neoplasia", "Benign and Malignant Neoplasia", "Uncontrolled clonal growth with dysplasia, invasion, and metastasis distinguishing malignancy.", "Benign tumors are encapsulated and noninvasive. Carcinoma in situ lacks basement membrane breach.", { ...S, chapter: "Neoplasia", section: "Characteristics" }),
  c("tumor_staging_and_grading", PATH, "Neoplasia", "Tumor Staging and Grading", "Anatomic extent (TNM) and histologic grade predicting prognosis and guiding therapy.", "Stage reflects spread; grade reflects differentiation. Lymph node involvement upstages most solid tumors.", { ...S, chapter: "Neoplasia", section: "Staging" }),
  c("atherosclerosis_pathogenesis", PATH, "Cardiovascular Pathology", "Atherosclerosis Pathogenesis", "Endothelial dysfunction, lipid accumulation, inflammatory infiltration, and plaque rupture in arterial disease.", "Stable plaques have thick fibrous caps. Rupture exposes thrombogenic lipid core causing acute coronary events.", { ...S, chapter: "Atherosclerosis", section: "Pathogenesis" }),
  c("myocardial_infarction_pathology", PATH, "Cardiovascular Pathology", "Myocardial Infarction Pathology", "Coagulative necrosis with wavefront progression, reperfusion injury, and healing by granulation tissue.", "Transmural infarcts involve full wall thickness. Troponin rise reflects cardiomyocyte necrosis.", { ...S, chapter: "Myocardial Infarction", section: "Pathology" }),
  c("pneumonia_and_lung_abscess", PATH, "Pulmonary Pathology", "Pneumonia and Lung Abscess Pathology", "Consolidation patterns from infectious agents with lobar, bronchopneumonic, and interstitial variants.", "Aspiration pneumonia involves dependent segments. Abscesses form cavitary necrotic collections.", { ...S, chapter: "Pneumonia", section: "Pathology" }),
  c("copd_and_emphysema_pathology", PATH, "Pulmonary Pathology", "COPD and Emphysema Pathology", "Chronic bronchitis with mucous gland hypertrophy versus alveolar wall destruction in emphysema.", "Centriacinar emphysema associates with smoking. Alpha-1 antitrypsin deficiency causes panacinar disease.", { ...S, chapter: "COPD", section: "Pathology" }),
  c("glomerular_disease_patterns", PATH, "Renal Pathology", "Glomerular Disease Patterns", "Nephritic versus nephrotic syndromes with proliferative, membranous, and crescentic histologic patterns.", "Nephrotic syndrome features heavy proteinuria and edema. Crescentic GN rapidly reduces GFR.", { ...S, chapter: "Glomerular Disease", section: "Patterns" }),
  c("acute_kidney_injury_pathology", PATH, "Renal Pathology", "Acute Kidney Injury Pathology", "Prerenal, intrinsic, and postrenal mechanisms with tubular necrosis and vascular causes.", "ATN shows muddy brown casts. Bilateral ureteral obstruction is a postrenal cause.", { ...S, chapter: "AKI", section: "Pathology" }),
  c("hepatitis_and_cirrhosis", PATH, "Hepatic Pathology", "Hepatitis and Cirrhosis", "Viral and toxic liver injury progressing to fibrosis, nodular regeneration, and portal hypertension.", "Cirrhosis disrupts architecture with regenerative nodules. Ascites reflects portal hypertension and hypoalbuminemia.", { ...S, chapter: "Liver Disease", section: "Cirrhosis" }),
  c("peptic_ulcer_and_ibd_pathology", PATH, "GI Pathology", "Peptic Ulcer and IBD Pathology", "Mucosal erosion from acid-pepsin injury versus chronic transmural inflammation in Crohn and ulcerative colitis.", "H. pylori predisposes to gastric and duodenal ulcers. Crohn skip lesions contrast continuous colitis in UC.", { ...S, chapter: "GI Pathology", section: "Ulcer and IBD" }),
  c("diabetes_mellitus_complications", PATH, "Endocrine Pathology", "Diabetes Mellitus Complications", "Microvascular and macrovascular damage including nephropathy, retinopathy, neuropathy, and accelerated atherosclerosis.", "Nonenzymatic glycation underlies microvascular injury. Diabetic ketoacidosis reflects insulin deficiency.", { ...S, chapter: "Diabetes", section: "Complications" }),
  c("anemia_classification_pathology", PATH, "Hematologic Pathology", "Anemia Classification and Pathology", "Microcytic, normocytic, and macrocytic anemias with hemolytic and production failure mechanisms.", "Iron deficiency is microcytic hypochromic. B12 or folate deficiency causes megaloblastic macrocytosis.", { ...S, chapter: "Anemia", section: "Classification" }),
  c("coagulation_disorders", PATH, "Hematologic Pathology", "Coagulation Disorders", "Inherited and acquired defects in platelet function, coagulation factors, and fibrinolysis causing bleeding or thrombosis.", "Hemophilia A is factor VIII deficiency. DIC consumes clotting factors and platelets.", { ...S, chapter: "Coagulation", section: "Disorders" }),
  c("cns_stroke_and_hemorrhage", PATH, "Neuropathology", "CNS Stroke and Hemorrhage", "Ischemic infarction with liquefactive necrosis versus intraparenchymal and subarachnoid hemorrhage.", "Embolic strokes are sudden and maximal at onset. Berry aneurysm rupture causes subarachnoid hemorrhage.", { ...S, chapter: "Stroke", section: "Pathology" }),
  c("neurodegenerative_disease_pathology", PATH, "Neuropathology", "Neurodegenerative Disease Pathology", "Protein aggregation disorders including Alzheimer, Parkinson, and prion diseases with selective neuronal loss.", "Alzheimer shows amyloid plaques and neurofibrillary tangles. Lewy bodies characterize Parkinson disease.", { ...S, chapter: "Neurodegeneration", section: "Pathology" }),

  // Microbiology & Infectious Disease (10)
  c("bacterial_cell_structure", MICRO, "Bacteriology", "Bacterial Cell Structure", "Peptidoglycan cell wall, membranes, flagella, pili, and spore formation distinguishing gram stain groups.", "Gram-positive thick peptidoglycan retains crystal violet. Endospores resist heat and disinfectants.", { ...S, chapter: "Bacteriology", section: "Structure" }),
  c("viral_replication_cycles", MICRO, "Virology", "Viral Replication Cycles", "Attachment, entry, genome replication, assembly, and release with lytic versus lysogenic strategies.", "Retroviruses integrate proviral DNA. Latent herpesviruses reactivate under immunosuppression.", { ...S, chapter: "Virology", section: "Replication" }),
  c("fungal_and_parasitic_overview", MICRO, "Mycology and Parasitology", "Fungal and Parasitic Overview", "Eukaryotic pathogens with distinctive morphology, life cycles, and host tissue tropism.", "Dimorphic fungi switch forms with temperature. Plasmodium life cycle involves mosquito and human hosts.", { ...S, chapter: "Parasitology", section: "Overview" }),
  c("normal_flora_and_opportunistic_infection", MICRO, "Host-Microbe Interactions", "Normal Flora and Opportunistic Infection", "Commensal organisms preventing colonization versus overgrowth causing disease when barriers fail.", "C. difficile colitis follows antibiotic disruption. Immunocompromise enables opportunistic infections.", { ...S, chapter: "Microbiome", section: "Opportunistic" }),
  c("staphylococcus_and_streptococcus", MICRO, "Gram-Positive Cocci", "Staphylococcus and Streptococcus", "Catalase-positive staphylococci versus catalase-negative streptococci with toxin and invasive syndromes.", "S. aureus causes skin abscess and endocarditis. Streptococcal pharyngitis risks rheumatic fever.", { ...S, chapter: "Gram-Positive", section: "Cocci" }),
  c("enteric_gram_negative_rods", MICRO, "Gram-Negative Rods", "Enteric Gram-Negative Rods", "Lactose fermenters and nonfermenters causing UTI, gastroenteritis, and sepsis.", "E. coli UTI ascends from perineum. Salmonella and Shigella cause dysenteric syndromes.", { ...S, chapter: "Gram-Negative", section: "Enterics" }),
  c("mycobacteria_and_acid_fast", MICRO, "Atypical Bacteria", "Mycobacteria and Acid-Fast Organisms", "Lipid-rich cell walls requiring acid-fast staining with slow growth and granulomatous host response.", "M. tuberculosis forms caseating granulomas. MAC infects advanced HIV patients.", { ...S, chapter: "Mycobacteria", section: "Overview" }),
  c("hiv_and_immunodeficiency_viruses", MICRO, "Retroviruses", "HIV and Immunodeficiency Viruses", "CD4 tropism, reverse transcription, and progressive immunodeficiency with opportunistic disease.", "HIV fusion requires CD4 and co-receptors. AIDS defines severe CD4 depletion with defining illnesses.", { ...S, chapter: "HIV", section: "Pathogenesis" }),
  c("vaccine_principles", MICRO, "Immunoprophylaxis", "Vaccine Principles", "Live attenuated, inactivated, subunit, and mRNA vaccines inducing protective adaptive immunity.", "Live vaccines contraindicated in pregnancy and severe immunodeficiency. Herd immunity limits transmission.", { ...S, chapter: "Vaccines", section: "Types" }),
  c("healthcare_associated_infections", MICRO, "Clinical Microbiology", "Healthcare-Associated Infections", "Nosocomial pathogens, device-related biofilms, and infection control measures in hospitals.", "Catheter-related UTI is common nosocomial infection. MRSA and VRE require contact precautions.", { ...S, chapter: "Nosocomial", section: "Prevention" }),

  // Immunology (8)
  c("innate_immunity_pattern_recognition", IMMUNO, "Innate Immunity", "Innate Immunity and Pattern Recognition", "TLRs and complement recognizing PAMPs and initiating rapid inflammatory responses.", "Innate immunity lacks antigen specificity. Complement opsonizes and lyses certain bacteria.", { ...S, chapter: "Innate Immunity", section: "PRRs" }),
  c("adaptive_immunity_overview", IMMUNO, "Adaptive Immunity", "Adaptive Immunity Overview", "B and T lymphocyte clonal selection generating antigen-specific memory.", "Primary response is slower; secondary is faster and stronger. Memory cells underpin vaccination.", { ...S, chapter: "Adaptive Immunity", section: "Overview" }),
  c("mhc_and_antigen_presentation", IMMUNO, "Antigen Presentation", "MHC and Antigen Presentation", "Class I presentation to CD8 T cells and class II to CD4 T cells linking innate detection to adaptive response.", "MHC I presents endogenous peptides. MHC II presents exogenous antigens from phagosomes.", { ...S, chapter: "MHC", section: "Presentation" }),
  c("humoral_immunity_antibodies", IMMUNO, "Humoral Immunity", "Humoral Immunity and Antibodies", "B cell differentiation to plasma cells producing IgM, IgG, IgA, IgE, and IgD with effector functions.", "IgG crosses placenta providing neonatal immunity. IgE mediates type I hypersensitivity.", { ...S, chapter: "Antibodies", section: "Classes" }),
  c("cell_mediated_immunity", IMMUNO, "Cell-Mediated Immunity", "Cell-Mediated Immunity", "CD4 helper and CD8 cytotoxic T cell activation, cytokine networks, and intracellular pathogen control.", "Th1 cells activate macrophages for intracellular bacteria. CTLs kill virus-infected cells.", { ...S, chapter: "T Cells", section: "Functions" }),
  c("hypersensitivity_reactions", IMMUNO, "Hypersensitivity", "Hypersensitivity Reactions", "Types I–IV immune-mediated tissue injury from immediate IgE to delayed T cell-mediated responses.", "Type I is anaphylaxis and allergy. Type IV includes contact dermatitis and TB skin test.", { ...S, chapter: "Hypersensitivity", section: "Types" }),
  c("autoimmunity_mechanisms", IMMUNO, "Autoimmunity", "Autoimmunity Mechanisms", "Loss of tolerance with molecular mimicry, epitope spreading, and genetic susceptibility producing autoimmune disease.", "SLE features anti-dsDNA and immune complexes. Rheumatoid arthritis involves synovial autoimmunity.", { ...S, chapter: "Autoimmunity", section: "Mechanisms" }),
  c("transplant_immunology_rejection", IMMUNO, "Transplantation", "Transplant Immunology and Rejection", "Hyperacute, acute, and chronic rejection mediated by preformed antibodies and T cell responses.", "Hyperacute rejection is immediate and antibody mediated. Immunosuppression prevents acute cellular rejection.", { ...S, chapter: "Transplant", section: "Rejection" }),

  // Neuroscience (9)
  c("neuroanatomy_brain_regions", NEURO, "Neuroanatomy", "Brain Regions and Functional Anatomy", "Cerebral lobes, basal ganglia, thalamus, brainstem, and cerebellum with major functional roles.", "Frontal lobe governs executive function. Brainstem houses vital cardiorespiratory centers.", { ...O, chapter: "13", section: "13.3" }),
  c("spinal_cord_tracts", NEURO, "Neuroanatomy", "Spinal Cord Tracts", "Ascending sensory and descending motor pathways with somatotopic organization.", "Lateral corticospinal tract mediates voluntary motor control. Dorsal columns carry proprioception.", { ...O, chapter: "13", section: "13.4" }),
  c("cranial_nerve_functions", NEURO, "Neuroanatomy", "Cranial Nerve Functions", "Twelve cranial nerves with sensory, motor, and autonomic components tested clinically.", "CN III palsy causes ptosis and down-out eye. Facial nerve lesions distinguish upper versus lower motor patterns.", { ...O, chapter: "13", section: "13.5" }),
  c("sensory_systems_overview", NEURO, "Sensory Neuroscience", "Sensory Systems Overview", "Special and somatic senses transducing stimuli via receptor potentials and labeled lines.", "Receptive fields determine spatial resolution. Lateral inhibition enhances contrast.", { ...O, chapter: "14", section: "14.1" }),
  c("motor_systems_and_movement", NEURO, "Motor Neuroscience", "Motor Systems and Movement", "Upper and lower motor neuron hierarchy, cerebellar coordination, and basal ganglia motor loops.", "UMN lesions cause spasticity and hyperreflexia. Basal ganglia disorders alter initiation and tone.", { ...O, chapter: "13", section: "13.6" }),
  c("autonomic_nervous_system_neuro", NEURO, "Autonomic Neuroscience", "Autonomic Nervous System Organization", "Sympathetic and parasympathetic divisions with ganglionic synapses and target organ effects.", "Sympathetic activation increases heart rate and bronchodilation. Parasympathetic stimulates digestion.", { ...O, chapter: "15", section: "15.1" }),
  c("neurotransmitters_and_receptors", NEURO, "Chemical Neuroscience", "Neurotransmitters and Receptors", "Amino acid, monoamine, and peptide signaling with ionotropic and metabotropic receptor classes.", "Glutamate is primary excitatory transmitter. Dopamine pathways relate to reward and movement.", { ...O, chapter: "12", section: "12.5" }),
  c("sleep_and_consciousness", NEURO, "Systems Neuroscience", "Sleep and Consciousness", "Wake-sleep architecture, reticular activating system, and EEG correlates of arousal states.", "REM sleep features vivid dreams and paralysis. Coma reflects diffuse arousal system dysfunction.", { ...O, chapter: "13", section: "13.7" }),
  c("pain_and_nociception", NEURO, "Sensory Neuroscience", "Pain and Nociception", "Nociceptor activation, spinal gate control, and central sensitization producing acute and chronic pain.", "Referred pain follows convergent spinal pathways. Opioids modulate pain at spinal and supraspinal sites.", { ...O, chapter: "14", section: "14.3" }),

  // Genetics & Molecular Medicine (9)
  c("mendelian_inheritance_patterns", GENETICS, "Medical Genetics", "Mendelian Inheritance Patterns", "Autosomal dominant, autosomal recessive, and X-linked transmission with pedigree interpretation.", "Dominant disorders often involve haploinsufficiency. Consanguinity increases recessive disease risk.", { ...S, chapter: "Genetics", section: "Mendelian" }),
  c("chromosomal_abnormalities", GENETICS, "Cytogenetics", "Chromosomal Abnormalities", "Aneuploidy, translocations, and microdeletions causing syndromic disease.", "Trisomy 21 causes Down syndrome. Philadelphia chromosome t(9;22) defines CML.", { ...S, chapter: "Cytogenetics", section: "Abnormalities" }),
  c("dna_repair_and_cancer_predisposition", GENETICS, "Molecular Genetics", "DNA Repair and Cancer Predisposition", "Mismatch, nucleotide excision, and double-strand break repair defects increasing mutation and malignancy risk.", "BRCA mutations impair homologous recombination. Lynch syndrome reflects mismatch repair defects.", { ...S, chapter: "DNA Repair", section: "Syndromes" }),
  c("gene_expression_regulation", GENETICS, "Molecular Biology", "Gene Expression Regulation", "Transcription factors, enhancers, epigenetic marks, and RNA processing controlling protein output.", "Methylation silences promoters. Alternative splicing generates protein diversity from one gene.", { ...S, chapter: "Gene Regulation", section: "Mechanisms" }),
  c("population_genetics_and_hwe", GENETICS, "Population Genetics", "Population Genetics and Hardy-Weinberg", "Allele frequencies in ideal populations and factors disturbing equilibrium including selection and drift.", "Hardy-Weinberg assumes random mating and large population. Carrier frequency informs screening programs.", { ...S, chapter: "Population Genetics", section: "HWE" }),
  c("pharmacogenomics", GENETICS, "Pharmacogenomics", "Pharmacogenomics", "Genetic variants altering drug metabolism, receptor response, and adverse effect susceptibility.", "G6PD deficiency causes hemolysis with oxidant drugs. TPMT variants affect thiopurine toxicity.", { ...S, chapter: "Pharmacogenomics", section: "Examples" }),
  c("trinucleotide_repeat_disorders", GENETICS, "Molecular Genetics", "Trinucleotide Repeat Disorders", "Unstable expansions causing anticipation in Huntington disease, fragile X, and myotonic dystrophy.", "Anticipation is earlier onset in successive generations. Huntington CAG repeats expand in paternal transmission.", { ...S, chapter: "Repeat Disorders", section: "Overview" }),
  c("imprinting_and_uniparental_disomy", GENETICS, "Epigenetics", "Genomic Imprinting and Uniparental Disomy", "Parent-of-origin-specific gene expression and chromosome pair from one parent causing disease.", "Prader-Willi versus Angelman reflect 15q deletion parent of origin. UPD can mimic deletions.", { ...S, chapter: "Imprinting", section: "Mechanisms" }),
  c("molecular_diagnostic_techniques", GENETICS, "Diagnostics", "Molecular Diagnostic Techniques", "PCR, sequencing, microarrays, and CRISPR-based assays detecting mutations and pathogens.", "PCR amplifies specific DNA for rapid diagnosis. Next-generation sequencing enables panel testing.", { ...S, chapter: "Molecular Diagnostics", section: "Techniques" }),

  // Behavioral Science & Epidemiology (9)
  c("study_designs_clinical_research", BEHAV, "Epidemiology", "Clinical Study Designs", "Cross-sectional, case-control, cohort, and randomized controlled trial designs with bias considerations.", "RCTs minimize confounding via randomization. Case-control studies are efficient for rare outcomes.", { ...S, chapter: "Epidemiology", section: "Study Designs" }),
  c("measures_of_disease_frequency", BEHAV, "Epidemiology", "Measures of Disease Frequency", "Incidence, prevalence, mortality, and morbidity quantifying population health burden.", "Prevalence rises with chronic disease duration. Incidence captures new cases over time.", { ...S, chapter: "Epidemiology", section: "Measures" }),
  c("screening_test_characteristics", BEHAV, "Biostatistics", "Screening Test Characteristics", "Sensitivity, specificity, predictive values, and likelihood ratios evaluating diagnostic tests.", "High sensitivity rules out disease (SNOUT). High specificity rules in disease (SPIN).", { ...S, chapter: "Screening", section: "Test Characteristics" }),
  c("bias_and_confounding", BEHAV, "Epidemiology", "Bias and Confounding", "Selection, information, and confounding biases threatening validity with stratification and matching remedies.", "Confounding distorts exposure-outcome association. Randomization balances known and unknown confounders.", { ...S, chapter: "Epidemiology", section: "Bias" }),
  c("learning_theory_and_conditioning", BEHAV, "Behavioral Science", "Learning Theory and Conditioning", "Classical and operant conditioning, reinforcement schedules, and extinction shaping behavior.", "Positive reinforcement increases behavior frequency. Classical conditioning pairs neutral and unconditioned stimuli.", { ...S, chapter: "Behavioral Science", section: "Learning" }),
  c("defense_mechanisms_psychology", BEHAV, "Behavioral Science", "Psychological Defense Mechanisms", "Unconscious strategies such as denial, projection, and sublimation reducing anxiety.", "Mature defenses include humor and altruism. Immature defenses include acting out and splitting.", { ...S, chapter: "Psychiatry", section: "Defense Mechanisms" }),
  c("motivation_and_stages_of_change", BEHAV, "Behavioral Science", "Motivation and Stages of Change", "Transtheoretical model from precontemplation through maintenance guiding health behavior counseling.", "Matching interventions to stage improves adherence. Relapse is expected in behavior change.", { ...S, chapter: "Behavioral Change", section: "Stages" }),
  c("medical_ethics_principles", BEHAV, "Medical Ethics", "Medical Ethics Principles", "Autonomy, beneficence, nonmaleficence, and justice applied to consent, confidentiality, and resource allocation.", "Informed consent requires capacity, disclosure, and voluntariness. Justice addresses fair distribution of care.", { ...S, chapter: "Ethics", section: "Principles" }),
  c("healthcare_delivery_and_quality", BEHAV, "Health Systems", "Healthcare Delivery and Quality", "Primary-secondary-tertiary prevention, quality improvement cycles, and patient safety systems.", "Primary prevention avoids disease onset. PDSA cycles drive continuous quality improvement.", { ...S, chapter: "Health Systems", section: "Quality" }),
];
